import {
  Dumbbell,
  Book,
  Brain,
  Droplets,
  Utensils,
  Bed,
  Code,
  Pencil,
  Music,
  Heart,
  Pill,
  Bike,
  Coffee,
  Laptop,
  PhoneOff,
  CigaretteOff,
  Banana,
  Paintbrush,
  Leaf,
  Glasses,
  ShoppingCart,
  Plane,
  Camera,
  Sun,
  Moon,
  Users,
  Handshake,
  Sprout,
  Wallet,
  Smile,
  Notebook,
  Play,
  Fish,
  ShieldCheck,
  Apple,
  Carrot,
  Candy,
  Beer,
  Wine,
  AlarmClock,
  Bell,
  BookOpen,
  Calendar,
  Castle,
  ChefHat,
  Clapperboard,
  Feather,
  GraduationCap,
  HandHeart,
  Headphones,
  HeartHandshake,
  Home,
  Lightbulb,
  Map,
  Mic,
  Mountain,
  PaintRoller,
  PawPrint,
  Scale,
  Store,
  ThermometerSun,
  Ticket,
  Train,
  TreePine,
  UtensilsCrossed,
  Waves,
} from "lucide-react";

export const habitIcons = [
  { name: "Exercise", icon: Dumbbell },
  { name: "Reading", icon: Book },
  { name: "Meditation", icon: Brain },
  { name: "Hydration", icon: Droplets },
  { name: "Healthy Eating", icon: Utensils },
  { name: "Sleep", icon: Bed },
  { name: "Coding", icon: Code },
  { name: "Writing", icon: Pencil },
  { name: "Music", icon: Music },
  { name: "Health", icon: Heart },
  { name: "Medication", icon: Pill },
  { name: "Cycling", icon: Bike },
  { name: "Coffee", icon: Coffee },
  { name: "Work", icon: Laptop },
  { name: "No Phone", icon: PhoneOff },
  { name: "No Smoking", icon: CigaretteOff },
  { name: "Fruits", icon: Banana },

  { name: "Painting", icon: Paintbrush },
  { name: "Gardening", icon: Leaf },
  { name: "No Glasses", icon: Glasses },
  { name: "Shopping", icon: ShoppingCart },
  { name: "Traveling", icon: Plane },
  { name: "Photography", icon: Camera },
  { name: "Sunlight Exposure", icon: Sun },
  { name: "Better Sleep", icon: Moon },
  { name: "Socializing", icon: Users },
  { name: "Helping Others", icon: Handshake },
  { name: "Plant Care", icon: Sprout },
  { name: "Saving Money", icon: Wallet },
  { name: "Smiling More", icon: Smile },
  { name: "Journaling", icon: Notebook },
  { name: "Relaxing", icon: Play },
  { name: "Eating Fish", icon: Fish },
  { name: "Safety", icon: ShieldCheck },
  { name: "Eating Apples", icon: Apple },
  { name: "Eating Vegetables", icon: Carrot },
  { name: "Avoiding Sweets", icon: Candy },
  { name: "No Alcohol", icon: Beer },
  { name: "No Wine", icon: Wine },
  { name: "Waking Up Early", icon: AlarmClock },
  { name: "Being on Time", icon: Bell },
  { name: "Learning", icon: BookOpen },
  { name: "Planning", icon: Calendar },
  { name: "Exploring", icon: Castle },
  { name: "Cooking", icon: ChefHat },
  { name: "Watching Movies", icon: Clapperboard },
  { name: "Taking Breaks", icon: Dumbbell },
  { name: "Writing Poetry", icon: Feather },
  { name: "Studying", icon: GraduationCap },
  { name: "Volunteering", icon: HandHeart },
  { name: "Listening to Podcasts", icon: Headphones },
  { name: "Kindness", icon: HeartHandshake },
  { name: "Spending Time at Home", icon: Home },
  { name: "Generating Ideas", icon: Lightbulb },
  { name: "Exploring New Places", icon: Map },
  { name: "Singing", icon: Mic },
  { name: "Hiking", icon: Mountain },
  { name: "Home Improvement", icon: PaintRoller },
  { name: "Caring for Pets", icon: PawPrint },
  { name: "Keeping a Healthy Weight", icon: Scale },

  { name: "Supporting Local Shops", icon: Store },
  { name: "Sun Protection", icon: ThermometerSun },
  { name: "Attending Events", icon: Ticket },
  { name: "Taking Public Transport", icon: Train },
  { name: "Spending Time in Nature", icon: TreePine },
  { name: "Cooking Balanced Meals", icon: UtensilsCrossed },
  { name: "Going to the Beach", icon: Waves },
];
