import {
  Dumbbell,
  Book,
  Brain,
  Droplets,
  Utensils,
  Bed,
  Code,
  Pencil,
  Music,
  Heart,
  Pill,
  Bike,
  Coffee,
  Laptop,
  Phone,
  Cigarette,
  Banana,
} from "lucide-react";

export const habitIcons = [
  { name: "Exercise", icon: Dumbbell },
  { name: "Reading", icon: Book },
  { name: "Meditation", icon: Brain },
  { name: "Hydration", icon: Droplets },
  { name: "Healthy Eating", icon: Utensils },
  { name: "Sleep", icon: Bed },
  { name: "Coding", icon: Code },
  { name: "Writing", icon: Pencil },
  { name: "Music", icon: Music },
  { name: "Health", icon: Heart },
  { name: "Medication", icon: Pill },
  { name: "Cycling", icon: Bike },
  { name: "Coffee", icon: Coffee },
  { name: "Work", icon: Laptop },
  { name: "No Phone", icon: Phone },
  { name: "No Smoking", icon: Cigarette },
  { name: "Fruits", icon: Banana },
];
